/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tutorial.xtext.ui.internal.XtextActivator;

public class TutorialUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.xtext.example.Tutorial");
	}

}
