/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class T2UiModule extends AbstractT2UiModule {

	public T2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
