/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.ide;

import at.ac.tuwien.big.T2RuntimeModule;
import at.ac.tuwien.big.T2StandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class T2IdeSetup extends T2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new T2RuntimeModule(), new T2IdeModule()));
	}
	
}
