/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTutorialScopeProvider extends DelegatingScopeProvider {
}
