/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tutorial2.xtext.ui.internal.XtextActivator;

public class T2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("at.ac.tuwien.big.T2");
	}

}
