/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class T2StandaloneSetup extends T2StandaloneSetupGenerated {

	public static void doSetup() {
		new T2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
