/*
 * generated by Xtext 2.27.0
 */
package at.ac.tuwien.big.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class T2GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class FactoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.Factory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFactoryAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFactoryKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOverseasitemKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOverseasitemAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cOverseasitemOverseasItemParserRuleCall_4_2_0 = (RuleCall)cOverseasitemAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOverseasitemAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cOverseasitemOverseasItemParserRuleCall_4_3_1_0 = (RuleCall)cOverseasitemAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cItemtypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cItemtypeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cItemtypeItemTypeParserRuleCall_5_2_0 = (RuleCall)cItemtypeAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cItemtypeAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cItemtypeItemTypeParserRuleCall_5_3_1_0 = (RuleCall)cItemtypeAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Factory returns Factory:
		//    {Factory}
		//    'Factory'
		//    name=EString
		//    '{'
		//        ('overseasitem' '{' overseasitem+=OverseasItem ( "," overseasitem+=OverseasItem)* '}' )?
		//        ('itemtype' '{' itemtype+=ItemType ( "," itemtype+=ItemType)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Factory}
		//'Factory'
		//name=EString
		//'{'
		//    ('overseasitem' '{' overseasitem+=OverseasItem ( "," overseasitem+=OverseasItem)* '}' )?
		//    ('itemtype' '{' itemtype+=ItemType ( "," itemtype+=ItemType)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Factory}
		public Action getFactoryAction_0() { return cFactoryAction_0; }
		
		//'Factory'
		public Keyword getFactoryKeyword_1() { return cFactoryKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('overseasitem' '{' overseasitem+=OverseasItem ( "," overseasitem+=OverseasItem)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'overseasitem'
		public Keyword getOverseasitemKeyword_4_0() { return cOverseasitemKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//overseasitem+=OverseasItem
		public Assignment getOverseasitemAssignment_4_2() { return cOverseasitemAssignment_4_2; }
		
		//OverseasItem
		public RuleCall getOverseasitemOverseasItemParserRuleCall_4_2_0() { return cOverseasitemOverseasItemParserRuleCall_4_2_0; }
		
		//( "," overseasitem+=OverseasItem)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//overseasitem+=OverseasItem
		public Assignment getOverseasitemAssignment_4_3_1() { return cOverseasitemAssignment_4_3_1; }
		
		//OverseasItem
		public RuleCall getOverseasitemOverseasItemParserRuleCall_4_3_1_0() { return cOverseasitemOverseasItemParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('itemtype' '{' itemtype+=ItemType ( "," itemtype+=ItemType)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'itemtype'
		public Keyword getItemtypeKeyword_5_0() { return cItemtypeKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//itemtype+=ItemType
		public Assignment getItemtypeAssignment_5_2() { return cItemtypeAssignment_5_2; }
		
		//ItemType
		public RuleCall getItemtypeItemTypeParserRuleCall_5_2_0() { return cItemtypeItemTypeParserRuleCall_5_2_0; }
		
		//( "," itemtype+=ItemType)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//itemtype+=ItemType
		public Assignment getItemtypeAssignment_5_3_1() { return cItemtypeAssignment_5_3_1; }
		
		//ItemType
		public RuleCall getItemtypeItemTypeParserRuleCall_5_3_1_0() { return cItemtypeItemTypeParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ItemTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.ItemType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBasicItemTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComplexItemTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ItemType returns ItemType:
		//    BasicItemType | ComplexItemType;
		@Override public ParserRule getRule() { return rule; }
		
		//BasicItemType | ComplexItemType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BasicItemType
		public RuleCall getBasicItemTypeParserRuleCall_0() { return cBasicItemTypeParserRuleCall_0; }
		
		//ComplexItemType
		public RuleCall getComplexItemTypeParserRuleCall_1() { return cComplexItemTypeParserRuleCall_1; }
	}
	public class OverseasItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.OverseasItem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOverseasItemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOverseasItemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOverseasmaterialKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOverseasmaterialAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cOverseasmaterialOverseasMaterialParserRuleCall_4_2_0 = (RuleCall)cOverseasmaterialAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOverseasmaterialAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cOverseasmaterialOverseasMaterialParserRuleCall_4_3_1_0 = (RuleCall)cOverseasmaterialAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//OverseasItem returns OverseasItem:
		//    {OverseasItem}
		//    'OverseasItem'
		//    name=EString
		//    '{'
		//        ('overseasmaterial' '{' overseasmaterial+=OverseasMaterial ( "," overseasmaterial+=OverseasMaterial)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{OverseasItem}
		//'OverseasItem'
		//name=EString
		//'{'
		//    ('overseasmaterial' '{' overseasmaterial+=OverseasMaterial ( "," overseasmaterial+=OverseasMaterial)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{OverseasItem}
		public Action getOverseasItemAction_0() { return cOverseasItemAction_0; }
		
		//'OverseasItem'
		public Keyword getOverseasItemKeyword_1() { return cOverseasItemKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('overseasmaterial' '{' overseasmaterial+=OverseasMaterial ( "," overseasmaterial+=OverseasMaterial)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'overseasmaterial'
		public Keyword getOverseasmaterialKeyword_4_0() { return cOverseasmaterialKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//overseasmaterial+=OverseasMaterial
		public Assignment getOverseasmaterialAssignment_4_2() { return cOverseasmaterialAssignment_4_2; }
		
		//OverseasMaterial
		public RuleCall getOverseasmaterialOverseasMaterialParserRuleCall_4_2_0() { return cOverseasmaterialOverseasMaterialParserRuleCall_4_2_0; }
		
		//( "," overseasmaterial+=OverseasMaterial)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//overseasmaterial+=OverseasMaterial
		public Assignment getOverseasmaterialAssignment_4_3_1() { return cOverseasmaterialAssignment_4_3_1; }
		
		//OverseasMaterial
		public RuleCall getOverseasmaterialOverseasMaterialParserRuleCall_4_3_1_0() { return cOverseasmaterialOverseasMaterialParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class OverseasMaterialElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.OverseasMaterial");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOverseasMaterialAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOverseasMaterialKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//OverseasMaterial returns OverseasMaterial:
		//    {OverseasMaterial}
		//    'OverseasMaterial'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{OverseasMaterial}
		//'OverseasMaterial'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{OverseasMaterial}
		public Action getOverseasMaterialAction_0() { return cOverseasMaterialAction_0; }
		
		//'OverseasMaterial'
		public Keyword getOverseasMaterialKeyword_1() { return cOverseasMaterialKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class BasicItemTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.BasicItemType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBasicItemTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBasicItemTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//BasicItemType returns BasicItemType:
		//    {BasicItemType}
		//    'BasicItemType'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{BasicItemType}
		//'BasicItemType'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{BasicItemType}
		public Action getBasicItemTypeAction_0() { return cBasicItemTypeAction_0; }
		
		//'BasicItemType'
		public Keyword getBasicItemTypeKeyword_1() { return cBasicItemTypeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ComplexItemTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.ComplexItemType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComplexItemTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cComplexItemTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOverseasitemKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOverseasitemAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cOverseasitemOverseasItemCrossReference_4_1_0 = (CrossReference)cOverseasitemAssignment_4_1.eContents().get(0);
		private final RuleCall cOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1 = (RuleCall)cOverseasitemOverseasItemCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOverseasmaterialKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOverseasmaterialAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cOverseasmaterialOverseasMaterialCrossReference_5_1_0 = (CrossReference)cOverseasmaterialAssignment_5_1.eContents().get(0);
		private final RuleCall cOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1 = (RuleCall)cOverseasmaterialOverseasMaterialCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cComponentKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cComponentAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cComponentComponentParserRuleCall_6_2_0 = (RuleCall)cComponentAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cComponentAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cComponentComponentParserRuleCall_6_3_1_0 = (RuleCall)cComponentAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ComplexItemType returns ComplexItemType:
		//    {ComplexItemType}
		//    'ComplexItemType'
		//    name=EString
		//    '{'
		//        ('overseasitem' overseasitem=[OverseasItem|EString])?
		//        ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		//        ('component' '{' component+=Component ( "," component+=Component)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ComplexItemType}
		//'ComplexItemType'
		//name=EString
		//'{'
		//    ('overseasitem' overseasitem=[OverseasItem|EString])?
		//    ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		//    ('component' '{' component+=Component ( "," component+=Component)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ComplexItemType}
		public Action getComplexItemTypeAction_0() { return cComplexItemTypeAction_0; }
		
		//'ComplexItemType'
		public Keyword getComplexItemTypeKeyword_1() { return cComplexItemTypeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('overseasitem' overseasitem=[OverseasItem|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'overseasitem'
		public Keyword getOverseasitemKeyword_4_0() { return cOverseasitemKeyword_4_0; }
		
		//overseasitem=[OverseasItem|EString]
		public Assignment getOverseasitemAssignment_4_1() { return cOverseasitemAssignment_4_1; }
		
		//[OverseasItem|EString]
		public CrossReference getOverseasitemOverseasItemCrossReference_4_1_0() { return cOverseasitemOverseasItemCrossReference_4_1_0; }
		
		//EString
		public RuleCall getOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1() { return cOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1; }
		
		//('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'overseasmaterial'
		public Keyword getOverseasmaterialKeyword_5_0() { return cOverseasmaterialKeyword_5_0; }
		
		//overseasmaterial=[OverseasMaterial|EString]
		public Assignment getOverseasmaterialAssignment_5_1() { return cOverseasmaterialAssignment_5_1; }
		
		//[OverseasMaterial|EString]
		public CrossReference getOverseasmaterialOverseasMaterialCrossReference_5_1_0() { return cOverseasmaterialOverseasMaterialCrossReference_5_1_0; }
		
		//EString
		public RuleCall getOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1() { return cOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1; }
		
		//('component' '{' component+=Component ( "," component+=Component)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'component'
		public Keyword getComponentKeyword_6_0() { return cComponentKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//component+=Component
		public Assignment getComponentAssignment_6_2() { return cComponentAssignment_6_2; }
		
		//Component
		public RuleCall getComponentComponentParserRuleCall_6_2_0() { return cComponentComponentParserRuleCall_6_2_0; }
		
		//( "," component+=Component)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//component+=Component
		public Assignment getComponentAssignment_6_3_1() { return cComponentAssignment_6_3_1; }
		
		//Component
		public RuleCall getComponentComponentParserRuleCall_6_3_1_0() { return cComponentComponentParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "at.ac.tuwien.big.T2.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComponentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cComponentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cItemtypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cItemtypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cItemtypeItemTypeCrossReference_3_1_0 = (CrossReference)cItemtypeAssignment_3_1.eContents().get(0);
		private final RuleCall cItemtypeItemTypeEStringParserRuleCall_3_1_0_1 = (RuleCall)cItemtypeItemTypeCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOverseasitemKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOverseasitemAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cOverseasitemOverseasItemCrossReference_4_1_0 = (CrossReference)cOverseasitemAssignment_4_1.eContents().get(0);
		private final RuleCall cOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1 = (RuleCall)cOverseasitemOverseasItemCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOverseasmaterialKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOverseasmaterialAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cOverseasmaterialOverseasMaterialCrossReference_5_1_0 = (CrossReference)cOverseasmaterialAssignment_5_1.eContents().get(0);
		private final RuleCall cOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1 = (RuleCall)cOverseasmaterialOverseasMaterialCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Component returns Component:
		//    {Component}
		//    'Component'
		//    '{'
		//        ('itemtype' itemtype=[ItemType|EString])?
		//        ('overseasitem' overseasitem=[OverseasItem|EString])?
		//        ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Component}
		//'Component'
		//'{'
		//    ('itemtype' itemtype=[ItemType|EString])?
		//    ('overseasitem' overseasitem=[OverseasItem|EString])?
		//    ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Component}
		public Action getComponentAction_0() { return cComponentAction_0; }
		
		//'Component'
		public Keyword getComponentKeyword_1() { return cComponentKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('itemtype' itemtype=[ItemType|EString])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'itemtype'
		public Keyword getItemtypeKeyword_3_0() { return cItemtypeKeyword_3_0; }
		
		//itemtype=[ItemType|EString]
		public Assignment getItemtypeAssignment_3_1() { return cItemtypeAssignment_3_1; }
		
		//[ItemType|EString]
		public CrossReference getItemtypeItemTypeCrossReference_3_1_0() { return cItemtypeItemTypeCrossReference_3_1_0; }
		
		//EString
		public RuleCall getItemtypeItemTypeEStringParserRuleCall_3_1_0_1() { return cItemtypeItemTypeEStringParserRuleCall_3_1_0_1; }
		
		//('overseasitem' overseasitem=[OverseasItem|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'overseasitem'
		public Keyword getOverseasitemKeyword_4_0() { return cOverseasitemKeyword_4_0; }
		
		//overseasitem=[OverseasItem|EString]
		public Assignment getOverseasitemAssignment_4_1() { return cOverseasitemAssignment_4_1; }
		
		//[OverseasItem|EString]
		public CrossReference getOverseasitemOverseasItemCrossReference_4_1_0() { return cOverseasitemOverseasItemCrossReference_4_1_0; }
		
		//EString
		public RuleCall getOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1() { return cOverseasitemOverseasItemEStringParserRuleCall_4_1_0_1; }
		
		//('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'overseasmaterial'
		public Keyword getOverseasmaterialKeyword_5_0() { return cOverseasmaterialKeyword_5_0; }
		
		//overseasmaterial=[OverseasMaterial|EString]
		public Assignment getOverseasmaterialAssignment_5_1() { return cOverseasmaterialAssignment_5_1; }
		
		//[OverseasMaterial|EString]
		public CrossReference getOverseasmaterialOverseasMaterialCrossReference_5_1_0() { return cOverseasmaterialOverseasMaterialCrossReference_5_1_0; }
		
		//EString
		public RuleCall getOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1() { return cOverseasmaterialOverseasMaterialEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final FactoryElements pFactory;
	private final ItemTypeElements pItemType;
	private final OverseasItemElements pOverseasItem;
	private final EStringElements pEString;
	private final OverseasMaterialElements pOverseasMaterial;
	private final BasicItemTypeElements pBasicItemType;
	private final ComplexItemTypeElements pComplexItemType;
	private final ComponentElements pComponent;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public T2GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFactory = new FactoryElements();
		this.pItemType = new ItemTypeElements();
		this.pOverseasItem = new OverseasItemElements();
		this.pEString = new EStringElements();
		this.pOverseasMaterial = new OverseasMaterialElements();
		this.pBasicItemType = new BasicItemTypeElements();
		this.pComplexItemType = new ComplexItemTypeElements();
		this.pComponent = new ComponentElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.ac.tuwien.big.T2".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Factory returns Factory:
	//    {Factory}
	//    'Factory'
	//    name=EString
	//    '{'
	//        ('overseasitem' '{' overseasitem+=OverseasItem ( "," overseasitem+=OverseasItem)* '}' )?
	//        ('itemtype' '{' itemtype+=ItemType ( "," itemtype+=ItemType)* '}' )?
	//    '}';
	public FactoryElements getFactoryAccess() {
		return pFactory;
	}
	
	public ParserRule getFactoryRule() {
		return getFactoryAccess().getRule();
	}
	
	//ItemType returns ItemType:
	//    BasicItemType | ComplexItemType;
	public ItemTypeElements getItemTypeAccess() {
		return pItemType;
	}
	
	public ParserRule getItemTypeRule() {
		return getItemTypeAccess().getRule();
	}
	
	//OverseasItem returns OverseasItem:
	//    {OverseasItem}
	//    'OverseasItem'
	//    name=EString
	//    '{'
	//        ('overseasmaterial' '{' overseasmaterial+=OverseasMaterial ( "," overseasmaterial+=OverseasMaterial)* '}' )?
	//    '}';
	public OverseasItemElements getOverseasItemAccess() {
		return pOverseasItem;
	}
	
	public ParserRule getOverseasItemRule() {
		return getOverseasItemAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//OverseasMaterial returns OverseasMaterial:
	//    {OverseasMaterial}
	//    'OverseasMaterial'
	//    name=EString;
	public OverseasMaterialElements getOverseasMaterialAccess() {
		return pOverseasMaterial;
	}
	
	public ParserRule getOverseasMaterialRule() {
		return getOverseasMaterialAccess().getRule();
	}
	
	//BasicItemType returns BasicItemType:
	//    {BasicItemType}
	//    'BasicItemType'
	//    name=EString;
	public BasicItemTypeElements getBasicItemTypeAccess() {
		return pBasicItemType;
	}
	
	public ParserRule getBasicItemTypeRule() {
		return getBasicItemTypeAccess().getRule();
	}
	
	//ComplexItemType returns ComplexItemType:
	//    {ComplexItemType}
	//    'ComplexItemType'
	//    name=EString
	//    '{'
	//        ('overseasitem' overseasitem=[OverseasItem|EString])?
	//        ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
	//        ('component' '{' component+=Component ( "," component+=Component)* '}' )?
	//    '}';
	public ComplexItemTypeElements getComplexItemTypeAccess() {
		return pComplexItemType;
	}
	
	public ParserRule getComplexItemTypeRule() {
		return getComplexItemTypeAccess().getRule();
	}
	
	//Component returns Component:
	//    {Component}
	//    'Component'
	//    '{'
	//        ('itemtype' itemtype=[ItemType|EString])?
	//        ('overseasitem' overseasitem=[OverseasItem|EString])?
	//        ('overseasmaterial' overseasmaterial=[OverseasMaterial|EString])?
	//    '}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
